
#
# NOTES:
#   Base Image:    mcr.microsoft.com/powershell:lts-nanoserver-ltsc2022
#                  mcr.microsoft.com/powershell:lts-nanoserver-1809
#                  mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-ltsc2022
#                  mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-1809
#   Application:   https://github.com/seabopo/psPodTester
#   Module Source: https://github.com/seabopo/psPodTester/releases/download/v1.1.2/psPodTester_v1.1.2.zip
#   Put the app in a subdirectory to avoid security errors during installation.
#
#    docker build -t "seabopo/pspodtester:nanoserver-1809-v1.2.0" -t "seabopo/pspodtester:nanoserver-1809" .
#    docker push seabopo/pspodtester:nanoserver-1809-v1.2.0
#

ARG BASE_IMAGE=mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-1809

FROM ${BASE_IMAGE}

ARG APP_VERSION=v1.2.0

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Write-Host "Application Version: $($env:APP_VERSION)"; \
    Write-Host "URI: https://github.com/seabopo/psPodTester/releases/download/$($env:APP_VERSION)/psPodTester_$($env:APP_VERSION).zip"; \
    New-Item \
        -ItemType directory \
        -Path "/psPodTester"; \
        Invoke-WebRequest \
        -Uri "https://github.com/seabopo/psPodTester/releases/download/$($env:APP_VERSION)/psPodTester_$($env:APP_VERSION).zip" \
        -OutFile "/psPodTester/psPodTester.zip"; \
    Expand-Archive \
        -Path "/psPodTester/psPodTester.zip" \
        -DestinationPath "/" \
        -Force; \
    Remove-Item \
        -Path "/psPodTester/psPodTester.zip" \
        -Force;

USER ContainerAdministrator

ENTRYPOINT ["pwsh.exe"]

CMD [ "-File", "C:/psPodTester/docker.ps1" ]

LABEL org.opencontainers.image.title="psPodTester" \
      org.opencontainers.image.description="A PowerShell module to test Windows container deployments." \
      org.opencontainers.image.documentation="https://github.com/seabopo/psPodTester" \
      org.opencontainers.image.base.name="${BASE_IMAGE}" \
      org.opencontainers.image.version="${APP_VERSION}" \
      org.opencontainers.image.url="https://hub.docker.com/r/seabopo/pspodtester" \
      org.opencontainers.image.vendor="seabopo" \
      org.opencontainers.image.authors="seabopo @ GitHub"
